# Generated by Django 2.2.6 on 2019-10-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='id',
        ),
        migrations.AlterField(
            model_name='city',
            name='city_abriviation',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='city_number',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
